### ISSUE TITLE
Showing error while clicking empty button

### ISSUE THREAD

**Issue by kartikaysaxena** [ControlCore-Project/concore-editor#135] opened 2023-03-07 03:40 UTC
To elaborate
<img width="1440" alt="Screenshot 2023-03-07 at 9 08 17 AM" src="https://user-images.githubusercontent.com/120778728/223314865-e3138aba-8c82-419b-93e1-2b1ff0b312af.png">
I can fix this

**Comment by parteekcoder** [comment] 2023-03-07 03:50
it only comes in development

And I think this issue is related to #125 , in which we are disabling `empty` when there is no graph

**Comment by pradeeban** [comment] 2023-03-07 04:08
Yes, as @parteekcoder mentioned, the correct fix should be to just disable that button when no study is loaded. While #138 should work in theory, we want to keep the UI uniform.

**Comment by pradeeban** [comment] 2023-03-07 04:10
Closing as a duplicate of #125.

**Comment by kartikaysaxena** [comment] 2023-03-07 04:10
@pradeeban As in my PR, it disables the functions of the button when properties go to null. I kinda think that works too.

**Closed** 2023-03-07 04:10 UTC

**Comment by pradeeban** [comment] 2023-03-07 04:15
@kartikaysaxena the fix should be to just disable the button to keep uniformity in the front-end. It should be a one-line change as done in #104.
