### ISSUE TITLE
The program editor opens the png images and binary files - rather than just the programs

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#71] opened 2023-02-07 16:59 UTC
1)open the app
2)click on  upload directory
3) upload files other than graphml

![image](https://user-images.githubusercontent.com/100110395/217312375-7354d6b4-b790-4075-a2c7-a55f05da773f.png)

**Comment by parteekcoder** [comment] 2023-02-07 17:01
@pradeeban please assign me the issues i am creating

**Comment by pradeeban** [comment] 2023-02-07 17:25
"Upload directory" uploads a whole directory to the browser, regardless of its contents. it does not look into whether it has a GraphML file or not. Therefore, we never encountered this problem and were unable to reproduce this issue.

Which browser did you use?

**Comment by parteekcoder** [comment] 2023-02-07 17:36
chrome,
yeah that I understand it is uploading directory but while opening file it should check if it can be opened rather crashing

**Comment by parteekcoder** [comment] 2023-02-07 17:37
![image](https://user-images.githubusercontent.com/100110395/217321672-749f8b32-99a3-46f0-9619-a41ed6f4b117.png)

clicking on any image file is not restricted and it crashed

**Comment by pradeeban** [comment] 2023-02-07 18:02
Interesting. I always get a window like the below, when a wrong file type is clicked.

![image](https://raw.githubusercontent.com/ControlCore-Project/concore-editor/main/figures/png-error.png)

Either way, your issue is valid. This should look for the extension types and open only those. For others, need to throw proper message.

**Comment by parteekcoder** [comment] 2023-02-07 18:14
check your console, in production it is not crashing but in development it does

![image](https://user-images.githubusercontent.com/100110395/217330676-695eeeee-0960-4406-b075-5c8b6cf37459.png)

**Comment by pradeeban** [comment] 2023-02-07 18:40
Got it. Please test and open the bug issues for the main deployed version of https://controlcore-project.github.io/concore-editor/ specifically. 

If it happens in local or dev branch, please indicate that clearly in the bug report. But I wouldn't want to spend more time on reporting issues on the dev branch or local deployments. It is possible that the dev branch becomes outdated at times.

**Comment by parteekcoder** [comment] 2023-02-07 19:07
i think this is only in development and behaves in unexpected way in different Systems

I don't have the access to add labels 

I also solved this issue and will create a PR for this issue once previous PR are get accepted

**Comment by pradeeban** [comment] 2023-02-09 16:32
Please ignore the browser console warnings.

Also, while it is good to check for the file type, it is assumed that the user is informed enough to choose programs (and not any random file such as a png file).

What we really lack here is documentation for concore-editor. If someone is accepted to work on the concore editor for GSoC 2023, they should pay attention to the documentation.

concore editor is a product of GSoC 2021 and GSoC 2022. While the contributors did an excellent job at implementing, the documentation was left as a second thought. This time, we will give a higher importance to documentation.

**Comment by parteekcoder** [comment] 2023-02-10 05:21
@pradeeban I can help in documentation and implementation as well 

But i think if user clicks unsupported files like png , we should give a warning to it , which makes our concore editor more robust towards any situation

So I request you to please open this issue so that we will enhance the performance

**Comment by parteekcoder** [comment] 2023-02-10 05:23
> Interesting. I always get a window like the below, when a wrong file type is clicked.
> 
> ![image](https://raw.githubusercontent.com/ControlCore-Project/concore-editor/main/figures/png-error.png)
> 
> Either way, your issue is valid. This should look for the extension types and open only those. For others, need to throw proper message.

as you mentioned here , it doesnot look nice that it concore editor is prone to some  bugs

**Comment by pradeeban** [comment] 2023-02-10 17:15
Reopened as you suggested. But edited the issue report to avoid "crashing" there as it does not really crash. @parteekcoder

**Comment by Aviral09** [comment] 2023-02-11 15:22
A simple extension check with a warning should be enough for this. As @pradeeban mentioned, this wasn't implemented in directory upload yet to support the ever-growing list of extensions. 
@parteekcoder you may add a simple alert for wrong extensions (other than the ones that pradeeban sir mentioned)

**Comment by Aviral09** [comment] 2023-02-11 15:28
> Got it. Please test and open the bug issues for the main deployed version of https://controlcore-project.github.io/concore-editor/ specifically.
> 
> If it happens in a local deployment or the dev branch, please indicate that clearly in the bug report. But I wouldn't want to spend more time on reporting issues on the dev branch or local deployments. It is possible that the dev branch becomes outdated at times.

@pradeeban it might be better to lock the main branch, invite all contributions to the dev branch or a separate gsoc branch and weekly sync the main with dev. This may help with keeping the main deployed version(production) safe.

**Comment by parteekcoder** [comment] 2023-02-11 15:37
> A simple extension check with a warning should be enough for this. As @pradeeban mentioned, this wasn't implemented in directory upload yet to support the ever-growing list of extensions. @parteekcoder you may add a simple alert for wrong extensions (other than the ones that pradeeban sir mentioned)

yeah I have added that I checked that if it is that file format which is suppurted then it is fine else show alert

**Comment by parteekcoder** [comment] 2023-02-11 15:37
@Aviral09  I will create a PR for this once previous PR's gets accepted

**Comment by parteekcoder** [comment] 2023-02-11 15:38
> > Got it. Please test and open the bug issues for the main deployed version of https://controlcore-project.github.io/concore-editor/ specifically.
> > If it happens in a local deployment or the dev branch, please indicate that clearly in the bug report. But I wouldn't want to spend more time on reporting issues on the dev branch or local deployments. It is possible that the dev branch becomes outdated at times.
> 
> @pradeeban it might be better to lock the main branch, invite all contributions to the dev branch or a separate gsoc branch and weekly sync the main with dev. This may help with keeping the main deployed version(production) safe.

yeah that's good idea

**Comment by pradeeban** [comment] 2023-02-11 16:13
> > Got it. Please test and open the bug issues for the main deployed version of https://controlcore-project.github.io/concore-editor/ specifically.
> > If it happens in a local deployment or the dev branch, please indicate that clearly in the bug report. But I wouldn't want to spend more time on reporting issues on the dev branch or local deployments. It is possible that the dev branch becomes outdated at times.
> 
> @pradeeban it might be better to lock the main branch, invite all contributions to the dev branch or a separate gsoc branch and weekly sync the main with dev. This may help with keeping the main deployed version(production) safe.

Good point, @Aviral09.

At this point, we consider the contributions from the GSoC contributors mostly for evaluation purposes. Merging them needs an extensive testing in all operating systems and is not productive except for critical bugs.

The approach I am taking is, merging the important PRs that I can test sufficiently. Others will remain open.

**Comment by pradeeban** [comment] 2023-02-11 16:15
> I will create a PR for this once previous PR's gets accepted

Hi @parteekcoder, please feel free to send PRs at your own pace. But as I mentioned earlier as well, please do not expect all the PRs to be merged. That will require additional testing on all the operating systems (and time, that we lack) and we are not in a rush except for critical bugs that we have reported in GitHub.

**Comment by parteekcoder** [comment] 2023-02-11 17:05
yeah @pradeeban I understand that before adding it to production it requires a lot of testing

ok I will find issues and create PR's for the same

**Comment by parteekcoder** [comment] 2023-02-13 08:09
hey @pradeeban you can check here https://parteekcoder.github.io/concore-editor/ my depoyment with latest changes

**Comment by pradeeban** [comment] 2023-02-13 15:29
Great to see you have deployed your version there. It saves a lot of our time in testing.

The issue I see with your current approach is "Wrong file extension" is thrown for acceptable files too. For example, a file with no extensions can be a valid program. So, while you attend to fix the issue of people mistakenly opening an invalid file, you are preventing people from opening valid programs too.

My recommendation on this bug you have reported is "won't fix" for now. We can come back to it when needed.

**Comment by parteekcoder** [comment] 2023-02-13 16:15
> Great to see you have deployed your version there. It saves a lot of our time in testing.
> 
> The issue I see with your current approach is "Wrong file extension" is thrown for acceptable files too. For example, a file with no extensions can be a valid program. So, while you attend to fix the issue of people mistakenly opening an invalid file, you are preventing people from opening valid programs too.
> 
> My recommendation on this bug you have reported is "won't fix" for now. We can come back to it when needed.

yeah , Actually I don't know that users are allowed to open files with no extensions also 
I have improved it . Once I have all details of file format allowed to user for opening I can improve it further

**Comment by Rahuljagwani** [comment] 2023-02-14 09:05
@pradeeban
I would like to mention that in README.md, in key features section it is written that concore-editor is able to export graphs as jpeg/png . So this issue is basically contradicting with README.md.

**Comment by parteekcoder** [comment] 2023-02-14 09:16
> @pradeeban I would like to mention that in README.md, in key features section it is written that concore-editor is able to export graphs as jpeg/png . So this issue is basically contradicting with README.md.

@Rahuljagwani this issue is that when try to open a png while it will show some unexpected output 

yes concore-editor have a key feature that you can export graphml file as jpeg/png and download in your device

**Comment by Rahuljagwani** [comment] 2023-02-14 09:26
> > @pradeeban I would like to mention that in README.md, in key features section it is written that concore-editor is able to export graphs as jpeg/png . So this issue is basically contradicting with README.md.
> 
> @Rahuljagwani this issue is that when try to open a png while it will show some unexpected output
> 
> yes concore-editor have a key feature that you can export graphml file as jpeg/png and download in your device

Thank you for clarification @parteekcoder. I misunderstood that.

**Comment by pradeeban** [comment] 2023-02-14 13:18
Yes, this is an export vs. open. You can export to JPEG/PNG images. But cannot (should not be able to) open them.

This issue is just that if someone double-clicks an image, currently, it will open as if it is a textual file. Ideally, as @parteekcoder reported (and has submitted a PR for), there should be just a warning not to let the users open the file. Other option is to open that in an image browser from within concore editor when double-clicks (which I strongly discourage as a useless feature at this point since no one needs to open a PNG image from within concore-editor).

**Comment by pradeeban** [comment] 2023-02-22 17:43
Fixed by #89.

Of course, we can keep adding more files. For example, .DS_STORE files created by MacOS. But this is ok for now.

**Closed by pradeeban** 2023-02-22 17:43 UTC
Labels: bug
